// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package user_mock is a generated GoMock package.
package user_mock

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/iDevoid/stygis/internal/constant/model"
	reflect "reflect"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Encrypt mocks base method
func (m *MockUserRepository) Encrypt(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Encrypt indicates an expected call of Encrypt
func (mr *MockUserRepositoryMockRecorder) Encrypt(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockUserRepository)(nil).Encrypt), user)
}
